version: '3'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://mongo:27017/chat
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
